project:
  type: website
  output-dir: docs
  
website:
  title: "Javier Patrón"
  navbar:
    background: dark
    foreground: primary
    left:
      - text: Home 
        href: index.qmd
      - text: Bio
        href: bio.qmd
      - text: Resume
        href: resume.qmd
      - text: shark
        href: SHARK.qmd
    
  page-footer: 
    left: "Copyright 2022, Javier Patrón" 
    right: 
      - icon: github
        href: https://github.com/javipatron 
        
format:
  html:
    theme: 
      light: Flatly
      dark: Solar
    css: styles.css
    toc: true

editor: visual

