project:
  type: website
  output-dir: docs
  

website:
  title: "Javier Patrón"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: bio.qmd
        text: Bio
      - href: images/Patron_Javier_InitialResume_8_20_22.pdf
        text: Resume
      - SHARK.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

