---
editor: visual
---

## Resume

[Download PDF](images/patron-javier-resume.pdf)

# EDUCATION

### *Master of Environmental Data Science*

##### June 2023

Bren School of Environmental Science & Management -- UC, Santa Barbara (UCSB).

*Highlighted Coursework:* Geospatial Analysis and Remote Sensing, Machine Learning in Environmental Science, Data Visualization and Communication, Carbon Footprint & Accounting, Environmental Policy Evaluation, Modeling Environmental Systems.

### *Bachelor of Mechanical and Electrical Engineering*

##### December 2017

Universidad Iberoamericana, Mexico City

Study Abroad: UNSW Sydney, Australia

Highlighted Coursework: Sustainability and Energy Efficiency, Computerized Innovation and Design, The Marine Environment, Global Finance, Sustainable and Renewable Energy, Process Technology and Automation.

# SKILLS & RECOGNITIONS

#### *Programming, Coding, & Data Analysis:*

Google Earth Engine, R, Python, GIS, SQL, Git (+ GitHub);

#### *Technical Coding Skills:*

Geospatial Analysis and Remote Sensing, Data Visualization, Machine Learning.

#### *GE Company Award:*

Nominated as "2021 Best Digital Worker" who embraced digital deployment in the region as an overachiever and a role model for the company.

# MASTER´S CAPSTONE DATA SCIENCE PROJECT

### *Developing a Data Pipeline for Kelp Forest Management and Cultivation*

##### Santa Barbara, CA (1/23 -- 6/23)

Role: Research and Data Scientist **\|** Client: [Ocean Rainforest](https://www.oceanrainforest.com/)

• Generated a dynamic, interactive, and open-source, data pipeline for running a geospatial model. This species distribution model helped us identify locations where kelp productivity and growth can be optimized for kelp restoration projects in the future.

• Synthesized datasets from the Santa Barbara Channel to examine spatial and temporal patterns in kelp-related variables, such as oceanographic factors, sea surface temperature, substrate and more.

# EXPERIENCE

### **Environmental Data Analyst -- [Silvestrum Climate Associates](https://www.silvestrum.com/),** remote (7/23 -- Present)

-   Specialize in Nature-Based Solutions for carbon projects, employing data science with a focus on remote sensing, GIS, and ocean hydrology. Develop and apply QC/QA procedures and environmental carbon models, enhancing project deliverables and outcomes.

-   Utilize machine learning and NASA ARSET for mapping blue carbon areas using GEE, create ArcPy scripts for global carbon stock estimation, and establish SOPs for mangrove quantification.

-   Transform data analysis into interactive visualizations for stakeholder engagement and decision-making. Innovate data management solutions to optimize team efficiency and Silvestrum project pipeline.

### **Intern, Data Project Manager -- [Silvestrum Climate Associates](https://www.silvestrum.com/),** remote (1/23 -- 6/23)

-   Focused on carbon accounting methodologies like Verra and Plan Vivo, statistical modeling, and empirical analysis for blue carbon ecosystems and carbon initiatives.

-   Collaborated as a Project Manager with experts in carbon science, land use, and remote sensing for a carbon project in Yucatan, Mexico, focusing on the technical side with analysis, GIS, and project development.

### *Intern, Collaboration with Center for Marine Biodiversity and Conservation: [CMBC](https://cmbc.ucsd.edu/)*

##### BCS, Mexico (4/22 -- 8/22)

• Bridging data science and management: An open-source integrated workflow for MPAs.

• Data-driven project mechanism to extract current MPA biodiversity health data from recreational divers.

### *Customer Support Lead -- [Current powered by GE](https://www.gecurrent.com/)*

##### *Mexico City, Mexico (6/20 -- 7/21)*

Global commissioning and tech-support team leader for GE Current ́s smart controls software.

-   Managed an 18-person global tech-support team, leading tech support operations supporting the business strategy new software and enhance IoT and AI solution capabilities.

-   USD \$5.8M in revenue recognition.

-   Technical leader for GE Current ́s most extensive gateway programming implementation, optimizing energy efficiency in over 1250 stores across Mexico using IoT and AI software, leading to substantial sustainable energy savings.

### *Digital Project Manager -- [Current powered by GE](https://www.led.com/)*

##### *Mexico City, Mexico (1/18 -- 6/20)*

Lead as a consultant and project manager for all Latin America Turn-Key digital projects.

• Sole LatAm digital resource for Daintree software implementation. Includes: Internal and external training, solutioning/ troubleshooting, and support for all current and completed projects.

• Client´s POC and project coordinator for third-party contractors, report project status, budget, and risks to GE leadership (LatAm, USA, AUS). Central POC. Lead coordination among third-party contractors.

### *Projects Intern -- [General Electric](https://www.ge.com/)*

##### *Mexico City, Mexico (5/17 -- 6/20)*

Project Management Intern / Order to Remittance team.

• Hand out weekly reports with the installation contractor, and field quality checks for the installation process.

• GE Lean Challenge competitor leveraging savings based on storage volume and shipment times.

# ADDITIONAL EXPERIENCE

### *Coral Farming Voluntary*

##### [Corals 4 Conservation](https://corals4conservation.org/). Mamanuca Islands, Fiji (9/21 -- 11/21)

Volunteering program to maintain, analyze and grow the coral nursery tables and mangrove reforestation programs with local marine biologists. Replanted over 500 corals with transects data practices.

### *Yachting*

##### Pacific Ocean (7/21 -- 7/22)

Sailed across the Pacific Ocean as Pro-Sailor in a 52ft racing boat, as a Team Manager, Tactician, and Watch captain. Participated in 3 international regattas (CaboRace, SoCal300, Transpac Regatta).

# ADDITIONAL SKILLS AND CERTIFICATIONS

### *Languages*

Fluent in English and Spanish

### *Certifications*

PADI Rescue Diver, Mexican Yacht Skipper License, Emergency First Response & CPR Certifications

### *Citizenship*

Mexican & Spanish

### *Other*

Authorized to work for any US employer (no sponsorship required)
